### ISSUE TITLE
Normalise domains

### ISSUE THREAD

**Issue by gordjw** [govau/GAlileo#10]
Non-normalised domains are resulting in some incorrect behaviour.
Filtering by www.dta.gov.au doesn't highlight dta.gov.au, for example.

Should it be fixed here, or upstream?

**Comment by maxious** [comment]
The groupings are defined by the domain column in the GEXF file. I would suggest this is handled in the data processing as there are probably other uses for a domain normalisation technique.

**Comment by gordjw** [comment]
Agreed.
